#ifndef __INCLUDE_INTR_H__

#define __INCLUDE_INTR_H__

#define GIC_BASE_ADDR (0xFF840000)

#define GIC_DISPATCH     (GIC_BASE_ADDR + 0x1000)
#define GIC_CPU          (GIC_BASE_ADDR + 0x2000)
#define GIC_VIRT_CONTROL (GIC_BASE_ADDR + 0x5000)
#define GIC_VIRT_CPU     (GIC_BASE_ADDR + 0x6000)

#define GICD_CTLR       (GIC_DISPATCH + 0x000)
#define GICD_TYPER      (GIC_DISPATCH + 0x004)
#define GICD_IIDR       (GIC_DISPATCH + 0x008)
#define GICD_IGROUPR    (GIC_DISPATCH + 0x080)
#define GICD_ISENABLER  (GIC_DISPATCH + 0x100)
#define GICD_ICENABLER  (GIC_DISPATCH + 0x180)
#define GICD_ISPENDR    (GIC_DISPATCH + 0x200)
#define GICD_ICPENDR    (GIC_DISPATCH + 0x280)
#define GICD_ISACTIVER  (GIC_DISPATCH + 0x300)
#define GICD_ICACTIVER  (GIC_DISPATCH + 0x380)
#define GICD_IPRIORITYR (GIC_DISPATCH + 0x400)
#define GICD_ITARGETSR  (GIC_DISPATCH + 0x800)
#define GICD_ICFGR      (GIC_DISPATCH + 0xC00)
#define GICD_SGIR       (GIC_DISPATCH + 0xF00)
#define GICD_CPENDSGIR  (GIC_DISPATCH + 0xF10)
#define GICD_SPENDSGIR  (GIC_DISPATCH + 0xF20)

#define GICC_CTRL       (GIC_CPU + 0x000)
#define GICC_PMR        (GIC_CPU + 0x004)
#define GICC_BPR        (GIC_CPU + 0x008)
#define GICC_IAR        (GIC_CPU + 0x00C)
#define GICC_EOIR       (GIC_CPU + 0x010)
#define GICC_RPR        (GIC_CPU + 0x014)
#define GICC_HPPIR      (GIC_CPU + 0x018)
#define GICC_APR        (GIC_CPU + 0x0D0)
#define GICC_IIDR       (GIC_CPU + 0x0FC)

#endif // !__INCLUDE_INTR_H__